### ISSUE TITLE
Can not read scheme Sublime Text 2.xml from '$ROOT_CONFIGS$/colors': Wrong color value: None)

### ISSUE THREAD

**Issue by rahulserver** [y-a-r-g/color-themes#19]
I am getting the error when I install the jar file in intellij idea(14.0.3) from the File->Import Settings menu and restarting IDE.

Check attach screenshot
![capture](https://cloud.githubusercontent.com/assets/5101740/11388751/78590428-935f-11e5-9f84-c49538f41684.PNG)

**Comment by y-a-r-g** [comment]
@rahulserver, could you please attach an archive you downloaded from the site? Probably it is corrupted or generated wrongly.
Do you have troubles with other themes?
What browser do you use?

**Comment by rahulserver** [comment]
I downloaded it from chrome. Here are the archive(s) attached(rename them to .jar instead of .txt as github did not allow me to upload .jar files)





[Monokai Sublime Text 3.txt](https://github.com/y-a-r-g/color-themes/files/43830/Monokai.Sublime.Text.3.txt)
[Sublime Text 2.txt](https://github.com/y-a-r-g/color-themes/files/43831/Sublime.Text.2.txt)

**Comment by rahulserver** [comment]
@y-a-r-g I tried two themes till now and both gave issues, so did not try others. Both archives attached in my former message

**Comment by y-a-r-g** [comment]
Well, Sublime Text 2 is broken, probably it was an error while migration, I will fix it.
Monokai Sublime Text 3 looks good, can you please try it again and post error message if one presenet?

**Comment by y-a-r-g** [comment]
I've fixed "Sublime Text 2" theme. "Monokai Sublime Text 3" works good for me.
