### ISSUE TITLE
Website frozen

### ISSUE THREAD

**Issue by metabuddy** [y-a-r-g/color-themes#24]
Hi,

Website has been frozen for over a day now.
Could you please look into it?

Thank you

**Comment by y-a-r-g** [comment]
I’ve checked it right now and it works for me. Google Analytics does not show any downtime. Can you please try to use proxy?

**Comment by metabuddy** [comment]
Same thing again today. I tried to connect via 3 different PCs, also tried standalone VPN and remote proxies... same results, some part of webpage loads and the loading animation is going on a loop.
here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/6424248/18956372/e33a6140-8663-11e6-8a2d-7350d9671746.png)

google analytics arent showing anything, because most likely its not a downtime - site is up, but it has functional issues - the part where schemes are stored is bugged.

**Comment by y-a-r-g** [comment]
Okay, lets investigate this. Please tell me, which browser do you use? Is javasctipt enabled? Open please developer tools in your browser and refresh page. Is there any error/warning messages?

**Comment by metabuddy** [comment]
I use google chrome, javascript is enabled.
Here are the error messages from dev console:
Internal server error 500 and database error.
![image](https://cloud.githubusercontent.com/assets/6424248/18982150/97404a0a-86ec-11e6-9e92-f83f7661eb83.png)

![image](https://cloud.githubusercontent.com/assets/6424248/18982178/b38d390c-86ec-11e6-8a01-ed79813ba229.png)

![image](https://cloud.githubusercontent.com/assets/6424248/18982228/0847ffae-86ed-11e6-8002-eb1c8baa7062.png)

**Comment by y-a-r-g** [comment]
Does error happen if you open http://color-themes.com/api/themes?offset=0&count=56&search=&order=popular directly or you can see JSON?

**Comment by metabuddy** [comment]
Then there is no error, screenshot below:

![image](https://cloud.githubusercontent.com/assets/6424248/18982678/9ff67422-86f0-11e6-9a50-c3a39ddeb607.png)

**Comment by y-a-r-g** [comment]
It’s looking strange, that raw request is working fine. Do you have any plugins installed that can break AJAX requests? Because server is working fine, as you can see and problem somewhere on your side.

**Comment by metabuddy** [comment]
Not sure... I have several addons for chrome, but I also tried with a fresh install of latest IE browser and firefox.
Here is the error when using firefox:
![image](https://cloud.githubusercontent.com/assets/6424248/19004118/ee0692de-875c-11e6-9f51-432907d590a1.png)

![image](https://cloud.githubusercontent.com/assets/6424248/19004188/4c7bf890-875d-11e6-86e8-1b4756d8f47d.png)
![image](https://cloud.githubusercontent.com/assets/6424248/19004198/5cc16b7c-875d-11e6-88ec-f4cfad7628d4.png)


and here are logs from IE browser:

![image](https://cloud.githubusercontent.com/assets/6424248/19004260/b2e82180-875d-11e6-8553-7e629a216534.png)

and here are logs from Edge browser:

![image](https://cloud.githubusercontent.com/assets/6424248/19004303/f8cbe240-875d-11e6-9964-d176c66bb352.png)

![image](https://cloud.githubusercontent.com/assets/6424248/19004314/01392abe-875e-11e6-971b-3d5d9fde231f.png)

**Comment by y-a-r-g** [comment]
Please write a message to info@color-themes.com and I'll send you back archive with themes.
