### ISSUE TITLE
Add "Update theme" feature

### ISSUE THREAD

**Issue by SerafimArts** [y-a-r-g/color-themes#26]
What about add "Update theme" button for users own themes? 

Like:

-----

# Theme name

> Author: The God

Download for _IDEA, Webstorm, PyCharm, RubyMine, PhpStorm and AppCode_

_Current version: 2_ 
**\[Select_another_version\] button** 
**\[Upload_new_version\] button** (<= for "owners")

### Generic
```
code highlighting example
```

...

**Comment by y-a-r-g** [comment]
The ide is good. But it's not profitable project and I'm not adding new functionality since have no time for that. If you can implement it, I will be glad to see your pull request.
